# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: DAtkinson
subtitle:
description: Personal blog of a Web Developer / System Administrator
author: Daniel Atkinson
language: en
timezone: Europe/London

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://datkinson.me
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: hexo-theme-hueman

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type:


# Menus
menu:
  Home: /
  # Delete this row if you don't want categories in your header nav bar
  Categories:
  About: /about

# Customize
customize:
  logo:
    width: 165
    height: 60
    url: images/logo-header.png
  theme_color: '#3b8dbd'
  highlight: androidstudio
  sidebar: left # sidebar position, options: left, right
  thumbnail: true # enable posts thumbnail, options: true, false
  favicon: # path to favicon
  social_links: # for more icons, please see http://fontawesome.io/icons/#brand
    twitter: https://twitter.com/HourdTasa
    #facebook: /
    #google-plus: /
    github: https://github.com/datkinson
    #weibo: /
    #rss: /

# Widgets
widgets:
  - recent_posts
  - category
  - archive
  - tag
  - tagcloud
  - links

# Search
search:
  path: search.xml
  field: post

# Comment
comment:
  disqus: disqus_Hkn2VeF179
  duoshuo: # enter duoshuo shortname here
  youyan: # enter youyan uid here

# Share
share: default # options: jiathis, bdshare, addtoany, default

# Plugins
plugins:
  fancybox: true # options: true, false
  scrollLoading: true # options: true, false
  google_analytics: UA-75527608-1
  baidu_analytics: # enter Baidu Analytics hash key

# Miscellaneous
miscellaneous:
  open_graph: # see http://ogp.me
    fb_app_id:
    fb_admins:
    twitter_id:
    google_plus:
  links:
    Hexo: http://hexo.io
